### ISSUE TITLE
Xrm.WebApi.createRecord results in POST Error

### ISSUE THREAD

**Issue by prasath2k4** [chnichol/mock-xrm#13]
I'm trying to create record via Xrm.Webapi using the mock-xrm library, it seems like the org name is not getting added to the url. See error attached
![WebApi Error](https://user-images.githubusercontent.com/7643239/96496954-89148480-127c-11eb-976f-1ec3547cf6b4.PNG)

**Comment by chnichol** [comment]
Thank you for surfacing the issue. It looks like you’re running an on-prem version. Is that correct?

**Comment by prasath2k4** [comment]
Yes :( any workaround?

**Comment by chnichol** [comment]
Please pull the latest and let me know if that works for you.

**Comment by prasath2k4** [comment]
Thanks for your help. When I tried to create an annotation record, it results with id is empty and attachment is not created. 
![image](https://user-images.githubusercontent.com/7643239/96544833-e25ed100-12d9-11eb-8114-0750751f877a.png)

**Comment by chnichol** [comment]
Updated the response data for: update, create, and delete apis. Let me know if you run into any other issues.

**Comment by chnichol** [comment]
Closing as resolved.
